version: '2'

services:
  sync:
    container_name: ${PROJECT_NAME}-sync
    image: docker.io/ubuntu:16.04
    volumes:
      - ./bin/:/root/bin/
      - ./etc/:/root/etc/
    network_mode: "host"
    command: /root/bin/sync -f /root/etc/externaldb.toml &

  convert:
    container_name: ${PROJECT_NAME}-convert
    image: docker.io/ubuntu:16.04
    depends_on:
      - sync
    volumes:
      - ./bin/:/root/bin/
      - ./etc/:/root/etc/
    network_mode: "host"
    command: /root/bin/convert -f /root/etc/externaldb.toml &

  rpc: # 存证项目使用
    container_name: ${PROJECT_NAME}-rpc
    image: docker.io/ubuntu:16.04
    volumes:
      - ./bin/:/root/bin/
      - ./etc/:/root/etc/
      - ./etc/mime.type:/etc/mime.types # 用于处理文件后缀
    network_mode: "host"
    command: /root/bin/rpc -f /root/etc/externaldb.toml &

  jrpc: # 浏览器项目使用
    container_name: ${PROJECT_NAME}-jrpc
    image: docker.io/ubuntu:16.04
    volumes:
      - ./bin/:/root/bin/
      - ./etc/:/root/etc/
    network_mode: "host"
    command: /root/bin/jrpc -f /root/etc/externaldb.toml &
