// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: convert.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exec     string   `protobuf:"bytes,1,opt,name=exec,proto3" json:"exec,omitempty"`
	All      []string `protobuf:"bytes,2,rep,name=all,proto3" json:"all,omitempty"`
	Generate []string `protobuf:"bytes,3,rep,name=generate,proto3" json:"generate,omitempty"`
}

func (x *ExecConfig) Reset() {
	*x = ExecConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_convert_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecConfig) ProtoMessage() {}

func (x *ExecConfig) ProtoReflect() protoreflect.Message {
	mi := &file_convert_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecConfig.ProtoReflect.Descriptor instead.
func (*ExecConfig) Descriptor() ([]byte, []int) {
	return file_convert_proto_rawDescGZIP(), []int{0}
}

func (x *ExecConfig) GetExec() string {
	if x != nil {
		return x.Exec
	}
	return ""
}

func (x *ExecConfig) GetAll() []string {
	if x != nil {
		return x.All
	}
	return nil
}

func (x *ExecConfig) GetGenerate() []string {
	if x != nil {
		return x.Generate
	}
	return nil
}

type StatConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stat string `protobuf:"bytes,1,opt,name=stat,proto3" json:"stat,omitempty"`
}

func (x *StatConfig) Reset() {
	*x = StatConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_convert_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatConfig) ProtoMessage() {}

func (x *StatConfig) ProtoReflect() protoreflect.Message {
	mi := &file_convert_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatConfig.ProtoReflect.Descriptor instead.
func (*StatConfig) Descriptor() ([]byte, []int) {
	return file_convert_proto_rawDescGZIP(), []int{1}
}

func (x *StatConfig) GetStat() string {
	if x != nil {
		return x.Stat
	}
	return ""
}

type AppConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EsHostRead    string        `protobuf:"bytes,1,opt,name=esHostRead,proto3" json:"esHostRead,omitempty"`
	EsHostWrite   string        `protobuf:"bytes,2,opt,name=esHostWrite,proto3" json:"esHostWrite,omitempty"`
	Symbol        string        `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	AppName       string        `protobuf:"bytes,4,opt,name=appName,proto3" json:"appName,omitempty"`
	ExecAddresses []string      `protobuf:"bytes,5,rep,name=execAddresses,proto3" json:"execAddresses,omitempty"`
	Para          string        `protobuf:"bytes,6,opt,name=para,proto3" json:"para,omitempty"`
	Prefix        string        `protobuf:"bytes,7,opt,name=prefix,proto3" json:"prefix,omitempty"`
	PrefixWrite   string        `protobuf:"bytes,8,opt,name=prefixWrite,proto3" json:"prefixWrite,omitempty"`
	StartSeq      int64         `protobuf:"varint,9,opt,name=startSeq,proto3" json:"startSeq,omitempty"`
	Data          []*ExecConfig `protobuf:"bytes,10,rep,name=data,proto3" json:"data,omitempty"`
	Stat          []*StatConfig `protobuf:"bytes,11,rep,name=stat,proto3" json:"stat,omitempty"`
	// 默认的处理插件
	DefaultExec string `protobuf:"bytes,12,opt,name=defaultExec,proto3" json:"defaultExec,omitempty"`
	// 是否处理非本链数据
	DealOtherChain bool `protobuf:"varint,13,opt,name=dealOtherChain,proto3" json:"dealOtherChain,omitempty"`
}

func (x *AppConfig) Reset() {
	*x = AppConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_convert_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppConfig) ProtoMessage() {}

func (x *AppConfig) ProtoReflect() protoreflect.Message {
	mi := &file_convert_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppConfig.ProtoReflect.Descriptor instead.
func (*AppConfig) Descriptor() ([]byte, []int) {
	return file_convert_proto_rawDescGZIP(), []int{2}
}

func (x *AppConfig) GetEsHostRead() string {
	if x != nil {
		return x.EsHostRead
	}
	return ""
}

func (x *AppConfig) GetEsHostWrite() string {
	if x != nil {
		return x.EsHostWrite
	}
	return ""
}

func (x *AppConfig) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *AppConfig) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *AppConfig) GetExecAddresses() []string {
	if x != nil {
		return x.ExecAddresses
	}
	return nil
}

func (x *AppConfig) GetPara() string {
	if x != nil {
		return x.Para
	}
	return ""
}

func (x *AppConfig) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *AppConfig) GetPrefixWrite() string {
	if x != nil {
		return x.PrefixWrite
	}
	return ""
}

func (x *AppConfig) GetStartSeq() int64 {
	if x != nil {
		return x.StartSeq
	}
	return 0
}

func (x *AppConfig) GetData() []*ExecConfig {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AppConfig) GetStat() []*StatConfig {
	if x != nil {
		return x.Stat
	}
	return nil
}

func (x *AppConfig) GetDefaultExec() string {
	if x != nil {
		return x.DefaultExec
	}
	return ""
}

func (x *AppConfig) GetDealOtherChain() bool {
	if x != nil {
		return x.DealOtherChain
	}
	return false
}

var File_convert_proto protoreflect.FileDescriptor

var file_convert_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a, 0x0a, 0x45, 0x78, 0x65, 0x63, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x78, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x65, 0x78, 0x65, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x6c, 0x6c, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x61, 0x6c, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x67, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x22, 0x20, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x73, 0x74, 0x61, 0x74, 0x22, 0xa7, 0x03, 0x0a, 0x09, 0x41, 0x70, 0x70,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x73, 0x48, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x73, 0x48, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x61, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x73, 0x48, 0x6f, 0x73, 0x74,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x73, 0x48,
	0x6f, 0x73, 0x74, 0x57, 0x72, 0x69, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x65, 0x78,
	0x65, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0d, 0x65, 0x78, 0x65, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x72, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x70, 0x61, 0x72, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x20, 0x0a, 0x0b,
	0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x57, 0x72, 0x69, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x57, 0x72, 0x69, 0x74, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x71, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x71, 0x12, 0x25, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x45, 0x78, 0x65, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x25, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x74, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x04, 0x73, 0x74, 0x61, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x45, 0x78, 0x65, 0x63, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x45, 0x78, 0x65, 0x63, 0x12, 0x26, 0x0a, 0x0e, 0x64, 0x65,
	0x61, 0x6c, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0e, 0x64, 0x65, 0x61, 0x6c, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x43, 0x68, 0x61,
	0x69, 0x6e, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_convert_proto_rawDescOnce sync.Once
	file_convert_proto_rawDescData = file_convert_proto_rawDesc
)

func file_convert_proto_rawDescGZIP() []byte {
	file_convert_proto_rawDescOnce.Do(func() {
		file_convert_proto_rawDescData = protoimpl.X.CompressGZIP(file_convert_proto_rawDescData)
	})
	return file_convert_proto_rawDescData
}

var file_convert_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_convert_proto_goTypes = []interface{}{
	(*ExecConfig)(nil), // 0: proto.ExecConfig
	(*StatConfig)(nil), // 1: proto.StatConfig
	(*AppConfig)(nil),  // 2: proto.AppConfig
}
var file_convert_proto_depIdxs = []int32{
	0, // 0: proto.AppConfig.data:type_name -> proto.ExecConfig
	1, // 1: proto.AppConfig.stat:type_name -> proto.StatConfig
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_convert_proto_init() }
func file_convert_proto_init() {
	if File_convert_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_convert_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_convert_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_convert_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_convert_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_convert_proto_goTypes,
		DependencyIndexes: file_convert_proto_depIdxs,
		MessageInfos:      file_convert_proto_msgTypes,
	}.Build()
	File_convert_proto = out.File
	file_convert_proto_rawDesc = nil
	file_convert_proto_goTypes = nil
	file_convert_proto_depIdxs = nil
}
