// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: exdbtransaction.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EsHostRead    string   `protobuf:"bytes,1,opt,name=esHostRead,proto3" json:"esHostRead,omitempty"`
	EsHostWrite   string   `protobuf:"bytes,2,opt,name=esHostWrite,proto3" json:"esHostWrite,omitempty"`
	ExecAddresses []string `protobuf:"bytes,5,rep,name=execAddresses,proto3" json:"execAddresses,omitempty"`
	Para          string   `protobuf:"bytes,6,opt,name=para,proto3" json:"para,omitempty"`
	Prefix        string   `protobuf:"bytes,7,opt,name=prefix,proto3" json:"prefix,omitempty"`
	PrefixWrite   string   `protobuf:"bytes,8,opt,name=prefixWrite,proto3" json:"prefixWrite,omitempty"`
	StartSeq      int64    `protobuf:"varint,9,opt,name=startSeq,proto3" json:"startSeq,omitempty"`
}

func (x *TransactionConfig) Reset() {
	*x = TransactionConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exdbtransaction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionConfig) ProtoMessage() {}

func (x *TransactionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_exdbtransaction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionConfig.ProtoReflect.Descriptor instead.
func (*TransactionConfig) Descriptor() ([]byte, []int) {
	return file_exdbtransaction_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionConfig) GetEsHostRead() string {
	if x != nil {
		return x.EsHostRead
	}
	return ""
}

func (x *TransactionConfig) GetEsHostWrite() string {
	if x != nil {
		return x.EsHostWrite
	}
	return ""
}

func (x *TransactionConfig) GetExecAddresses() []string {
	if x != nil {
		return x.ExecAddresses
	}
	return nil
}

func (x *TransactionConfig) GetPara() string {
	if x != nil {
		return x.Para
	}
	return ""
}

func (x *TransactionConfig) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *TransactionConfig) GetPrefixWrite() string {
	if x != nil {
		return x.PrefixWrite
	}
	return ""
}

func (x *TransactionConfig) GetStartSeq() int64 {
	if x != nil {
		return x.StartSeq
	}
	return 0
}

var File_exdbtransaction_proto protoreflect.FileDescriptor

var file_exdbtransaction_proto_rawDesc = []byte{
	0x0a, 0x15, 0x65, 0x78, 0x64, 0x62, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe5,
	0x01, 0x0a, 0x11, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x73, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65,
	0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x73, 0x48, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x61, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x73, 0x48, 0x6f, 0x73, 0x74, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x73, 0x48, 0x6f, 0x73,
	0x74, 0x57, 0x72, 0x69, 0x74, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x65, 0x78, 0x65, 0x63, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x65,
	0x78, 0x65, 0x63, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x72, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x72, 0x61,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x65, 0x66,
	0x69, 0x78, 0x57, 0x72, 0x69, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70,
	0x72, 0x65, 0x66, 0x69, 0x78, 0x57, 0x72, 0x69, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x53, 0x65, 0x71, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x53, 0x65, 0x71, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_exdbtransaction_proto_rawDescOnce sync.Once
	file_exdbtransaction_proto_rawDescData = file_exdbtransaction_proto_rawDesc
)

func file_exdbtransaction_proto_rawDescGZIP() []byte {
	file_exdbtransaction_proto_rawDescOnce.Do(func() {
		file_exdbtransaction_proto_rawDescData = protoimpl.X.CompressGZIP(file_exdbtransaction_proto_rawDescData)
	})
	return file_exdbtransaction_proto_rawDescData
}

var file_exdbtransaction_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_exdbtransaction_proto_goTypes = []interface{}{
	(*TransactionConfig)(nil), // 0: proto.TransactionConfig
}
var file_exdbtransaction_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_exdbtransaction_proto_init() }
func file_exdbtransaction_proto_init() {
	if File_exdbtransaction_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_exdbtransaction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_exdbtransaction_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exdbtransaction_proto_goTypes,
		DependencyIndexes: file_exdbtransaction_proto_depIdxs,
		MessageInfos:      file_exdbtransaction_proto_msgTypes,
	}.Build()
	File_exdbtransaction_proto = out.File
	file_exdbtransaction_proto_rawDesc = nil
	file_exdbtransaction_proto_goTypes = nil
	file_exdbtransaction_proto_depIdxs = nil
}
