package trade

// mapping
const (
	OrderMapping = `{
    "mappings":{
        "properties":{
            "height_index":{
                "type":"long"
            },
            "boardlot_amount":{
                "type":"long"
            },
            "ts":{
                "type":"long"
            },
            "min_boardlot":{
                "type":"long"
            },
            "asset_exec":{
                "type":"keyword"
            },
            "is_sell":{
                "type":"boolean"
            },
            "is_finished":{
                "type":"boolean"
            },
            "asset_symbol":{
                "type":"keyword"
            },
            "sell_id":{
                "type":"keyword"
            },
            "boardlot_price":{
                "type":"long"
            },
            "status":{
                "type":"keyword"
            },
            "index":{
                "type":"long"
            },
            "traded_boardlot":{
                "type":"long"
            },
            "owner":{
                "type":"keyword"
            },
            "send":{
                "type":"keyword"
            },
            "buy_id":{
                "type":"keyword"
            },
            "height":{
                "type":"long"
            },
            "block_hash":{
                "type":"keyword"
            },
            "tx_hash":{
                "type":"keyword"
            },
            "total_boardlot":{
                "type":"long"
            }
        }
    }
}`

	TradeTxMapping = `{
    "mappings":{
        "properties":{
            "block_hash":{
                "type":"keyword"
            },
            "buy_market":{
                "properties":{
                    "sellID":{
                        "type":"keyword"
                    },
                    "boardlotCnt":{
                        "type":"long"
                    }
                }
            },
            "sell_market":{
                "properties":{
                    "BuyID":{
                        "type":"keyword"
                    },
                    "boardlotCnt":{
                        "type":"long"
                    }
                }
            },
            "sell_limit":{
                "properties":{
                    "amountPerBoardlot":{
                        "type":"long"
                    },
                    "tokenSymbol":{
                        "type":"keyword"
                    },
                    "pricePerBoardlot":{
                        "type":"long"
                    },
                    "totalBoardlot":{
                        "type":"long"
                    },
                    "minBoardlot":{
                        "type":"long"
                    }
                }
            },
            "buy_limit":{
                "properties":{
                    "amountPerBoardlot":{
                        "type":"long"
                    },
                    "tokenSymbol":{
                        "type":"keyword"
                    },
                    "pricePerBoardlot":{
                        "type":"long"
                    },
                    "totalBoardlot":{
                        "type":"long"
                    },
                    "minBoardlot":{
                        "type":"long"
                    }
                }
            },
            "send":{
                "type":"keyword"
            },
            "index":{
                "type":"long"
            },
            "tx_hash":{
                "type":"keyword"
            },
            "ts":{
                "type":"long"
            },
            "height_index":{
                "type":"long"
            },
            "tx_type":{
                "type":"keyword"
            },
            "success":{
                "type":"boolean"
            },
            "height":{
                "type":"long"
            },
            "sell_revoke":{
                "properties":{
                    "sellID":{
                        "type":"keyword"
                    }
                }
            },
            "buy_revoke":{
                "properties":{
                    "buyID":{
                        "type":"keyword"
                    }
                }
            }
        }
    }
}`
	AssetMapping = `{
    "mappings":{
        "properties":{
            "asset_exec":{
                "type":"keyword"
            },
            "asset_symbol":{
                "type":"keyword"
            }
        }
    }
}`
)
