version: '2'

services:
  elasticsearch: # Elasticsearch Instance
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    volumes: # Persist ES data in seperate "esdata" volume
      - /root/es/data:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - "xpack.security.enabled=false"
    ports: # Expose Elasticsearch ports
      - "9300:9300"
      - "9200:9200"


