package unfreeze

// db
const (
	// SeqMapping unfreeze_seq/seq/
	SeqMapping = `{
    "mappings":{
        "properties":{
            "sync_seq":{
                "type":"long"
            }
        }
    }
}`

	// TxRecordMapping unfreeze_tx/unfreeze/
	TxRecordMapping = `{
    "mappings":{
        "properties":{
            "creator":{
                "type":"keyword"
            },
            "create":{
                "type":"object",
                "properties":{
                    "means":{
                        "type":"keyword"
                    },
                    "fix_amount":{
                        "type":"object",
                        "properties":{
                            "period":{
                                "type":"long"
                            },
                            "amount":{
                                "type":"long"
                            }
                        }
                    },
                    "left_proportion":{
                        "type":"object",
                        "properties":{
                            "period":{
                                "type":"long"
                            },
                            "tenThousandth":{
                                "type":"long"
                            }
                        }
                    },
                    "total_count":{
                        "type":"long"
                    },
                    "start_time":{
                        "type":"long"
                    },
                    "asset_symbol":{
                        "type":"keyword"
                    },
                    "asset_exec":{
                        "type":"keyword"
                    }
                }
            },
            "unfreeze_id":{
                "type":"keyword"
            },
            "block":{
                "type":"object",
                "properties":{
                    "hash":{
                        "type":"keyword"
                    },
                    "height":{
                        "type":"long"
                    },
                    "ts":{
                        "type":"long"
                    },
                    "index":{
                        "type":"long"
                    }
                }
            },
            "action_type":{
                "type":"keyword"
            },
            "beneficiary":{
                "type":"keyword"
            },
            "success":{
                "type":"boolean"
            },
            "withdraw":{
                "type":"object",
                "properties":{
                    "amount":{
                        "type":"long"
                    }
                }
            },
            "terminate":{
                "type":"object",
                "properties":{
                    "amount_left":{
                        "type":"long"
                    },
                    "amount_back":{
                        "type":"long"
                    }
                }
            }
        }
    }
}`
)
